remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: Harel's Blog
minimal_mistakes_skin: "default"

# Allow posts with future dates to be published
future: true

url: "https://fearthedeer9.github.io"
baseurl: ""
repository: "fearthedeer9/fearthedeer9.github.io"

include:
  - _includes
  - _layouts
  - _pages

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

permalink: /:year/:month/:day/:title/
paginate: 50

markdown: kramdown
kramdown:
  math_engine: mathjax

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      mathjax: true
      excerpt_separator: <!-- excerpt-end -->
main:
  - title: "Wiki"
    url: "/wiki.fearthedeer9.github.io/"

navbar:
  - title: "Wiki"
    url: "/wiki.fearthedeer9.github.io/"

author:
  name: "Harel Lidar"
  bio: "Harel's Blog"
  tagline: "AI Researcher • Machine Learning Engineer"
  description: "Exploring the frontiers of artificial intelligence through research and implementation. Specializing in neural architectures, 3D vision, and transformer models."
  github: "fearthedeer9"
  linkedin: "harel-lidar-3759b518a"  # Update this with your actual LinkedIn username
  email: "rllidar9@gmail.com"  # Update this with your actual email
