remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: Harel's Blog
minimal_mistakes_skin: "default"

url: "https://fearthedeer9.github.io"
baseurl: ""

include:
  - _includes
  - _layouts
  - _pages

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

permalink: /:year/:month/:day/:title/
paginate: 5

markdown: kramdown
kramdown:
  math_engine: mathjax

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      mathjax: true

main:
  - title: "Wiki"
    url: "/wiki.fearthedeer9.github.io/"

navbar:
  - title: "Wiki"
    url: "/wiki.fearthedeer9.github.io/"

author:
  name: "Harel Lidar"
  bio: "Harel's Blog"
