remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: Your Blog
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

search: true

# Navigation
navbar:
  - title: "Wiki"
    url: https://wiki.your-username.github.io

# Site Author
author:
  name: "Your Name"
  bio: "Your bio"
  avatar: "/assets/images/bio-photo.jpg"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
