remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: Harel's Blog
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

search: true

main:
  - title: "Wiki"
    url: "/wiki.fearthedeer9.github.io/"

# Navigation
navbar:
  - title: "Wiki"
    url: "/wiki.fearthedeer9.github.io/"

# Site Author
author:
  name: "Harel Lidar"
  bio: "Harel's Blog"
  avatar: "/assets/images/bio-photo.jpg"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
